# Generated by Django 5.1 on 2025-04-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_content_comment_text_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
