# Generated by Django 5.1 on 2025-04-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_communitypost_communitycomment_communitylike"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="communitylike",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="communitylike",
            name="post",
        ),
        migrations.RemoveField(
            model_name="communitylike",
            name="user",
        ),
        migrations.RemoveField(
            model_name="communitypost",
            name="user",
        ),
        migrations.DeleteModel(
            name="CommunityComment",
        ),
        migrations.DeleteModel(
            name="CommunityLike",
        ),
        migrations.DeleteModel(
            name="CommunityPost",
        ),
    ]
